### ISSUE TITLE
Error Open file from url

### ISSUE THREAD

**Issue by ogorodriguez** [quanteda/readtext#119]
I am following the vignette of readtext ([here](https://cran.r-project.org/web/packages/readtext/vignettes/readtext_vignette.html#reading-one-or-more-text-files)) and the example to read in text from urls is still not available.  I tried the following but got the resulting error.  

My idea was to fetch the pdf files listed on the website.  

Any help on the latter will be appreciated:

``` r
txt_url <- readtext("https://2017.hack.lu/archive/2012/*.pdf", encoding = "ISO-8859-1")
#> Error in readtext("https://2017.hack.lu/archive/2012/*.pdf", encoding = "ISO-8859-1"): could not find function "readtext"
```

Created on 2018-03-10 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by koheiw** [comment]
You cannot use wildcard in URL unless your web sever supports it (I have never seen something like that).

**Comment by kbenoit** [comment]
We should test more how the direct download from URLs works, when the target is a:
* directory
* zip file
* single file (this at least works)
