### ISSUE TITLE
Problems with Xpath 

### ISSUE THREAD

**Issue by cownr10r** [quanteda/readtext#129]
Dear Developers, 

I am having difficulties in getting readtext to recognize the Xpath within an xml file. I have included the link here [https://1drv.ms/u/s!Ai636WhvMoN5sUEm2cuimQSjzGbo](url). 

The complete path to the folder where .xml files live are: "~/Desktop/LFA/DATADATA". I have used the following commands in R on a mac"
```
DATA_DIR <- "~/Desktop/LFA/"
library(readtext)
documents <- readtext::readtext(paste0(DATA_DIR, "/DATADATA/*"), text_field = "//div[@type = 'section'][@n = '3']/p")
```
I get forward slashes and ellipses in response for the text, and when checking for characters
```
documents$text[1]
```
I get " " as a response. 

It is possible that my Xpath is incorrect. I have also tried the following Xpath from Oxygen XML Editor:
"/TEI/text[1]/body[1]/div[3]/p[1]"

Thanks for your help. 

Sincerely,
Mario

**Comment by amatsuo** [comment]
I had a look at the file but not sure which field you try to extract. What's your desired output from the code? The filed does not have `div`-tag.

**Comment by cownr10r** [comment]
Thanks for your reply, amatsuo,
It is my understanding from studying TEI that the div code is present with attributes. I have included the div with the attribute type and the attribute number.  I am trying to retrieve the text from the paragraph at div 3. 
<div type = "section" n="3">
<p> When I left school at the age of 18...
</p>
</div>

[sample xml.txt](https://github.com/quanteda/readtext/files/1976889/sample.xml.txt)

Thanks in advance for your help. 
Sincerely, 
Mario

**Comment by amatsuo** [comment]
The `sample.xml` can be extracted with the following steps:

1. Install the latest master from github:
    ```r
      devtools::install_github("quanteda/readtext")
    ```

2. Run the following command
    ```r
      readtext("./sample.xml", text_field =  "//*/d1:div[@n = '3']/d1:p") 
    ```

This version uses `xml2` for parsing xml and the default name for the first namespace is `d1`, and you need to use the name in xpath.

The output is:

```
## readtext object consisting of 1 document and 0 docvars.
## # data.frame [1 × 2]
##   doc_id     text               
##   <chr>      <chr>              
## 1 sample.xml "\"When I lef\"..."
```

The current CRAN version needs a slightly different syntax (use `namespace` argument for `XML::xmlParse`) because of the back end technology (`XML` vs `xml2`), but I won't show it as it will be deprecated soon.

**Comment by cownr10r** [comment]
Thank you, Aki Matsuo, for your help. I appreciate it!
Mario
