### ISSUE TITLE
ERROR: installing vignettes failed

### ISSUE THREAD

**Issue by AnarchistPenguin** [quanteda/readtext#153]
When I try to install the package with install.packages("readtext"), I get the following error:

`'\\home.ansatt.ntnu.no\sinaoz\Documents'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
* installing *source* package 'readtext' ...
** package 'readtext' successfully unpacked and MD5 sums checked
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'readtext'
    finding HTML links ... done
    as.character.readtext                   html  
    basename_unique                         html  
    cache_remote                            html  
    data_char_encodedtexts                  html  
    data_files_encodedtexts                 html  
    encoding                                html  
    get_nexis_html                          html  
    get_temp                                html  
    impute_types                            html  
    print.readtext                          html  
    readtext-package                        html  
    readtext                                html  
    finding level-2 HTML links ... done

    readtext_options                        html  
    sort_fields                             html  
** building package indices
** installing vignettes
Warning in file(con, "w") :
  cannot open file '\\home.ansatt.ntnu.no/sinaoz/Documents/R/win-library/3.5/readtext/doc/index.html': No such file or directory
Error in file(con, "w") : cannot open the connection
ERROR: installing vignettes failed
* removing '\\home.ansatt.ntnu.no/sinaoz/Documents/R/win-library/3.5/readtext'
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘readtext’ had non-zero exit status`

I tried to install with devtools but it has been over 45 minutes and the process is still going on.  Any ideas on how to solve the problem with vignette installation?

my session info:

`R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.2 tools_3.5.2   `

**Comment by kbenoit** [comment]
Hard to know what the problem is but it sounds like an R configuration issue.

You can try:
```r
install.packages("readtext", type = "binary")
```
or try it again now that we've just uploaded **readtext** 0.74 to CRAN.
