### ISSUE TITLE
readtext(source+"twitter") for tweets from 2016

### ISSUE THREAD

**Issue by sagarkumar16** [quanteda/readtext#161]
Hello, I'm trying to load a tweet body from a tweet stream that was collected in 2016 and whenever I try to run the readtext() function with "twitter" as the source, I get the error: 

> test_tweets = readtext("filepath/file.json", source = "twitter")
Error in value[[3L]](cond) : 
  Doesn't look like Tweets JSON file, trying general JSON.

**Comment by kbenoit** [comment]
Would be happy to help but we need to be able to reproduce the error. Can you send a few records from your file?

**Comment by sagarkumar16** [comment]
Yes, I'd be happy to - here you are. They've been changed from .json to .txt because Github doesn't support .json files.

[test.txt](https://github.com/quanteda/readtext/files/4110734/test.txt)
[2016-10-03.txt](https://github.com/quanteda/readtext/files/4110739/2016-10-03.txt)

**Comment by amatsuo** [comment]
These two files do not generate an error...
