### ISSUE TITLE
ERROR 'Readtext’ had non-zero exit status

### ISSUE THREAD

**Issue by ricoblanc1** [quanteda/readtext#162]
Hi All

I'm new to R, so I appreciate your help and patience. I am not able to install readtext. I've copied below the console information as well as my session information. Please help, thank you!

> install.packages("readtext", repo = 'https://mac.R-project.org')
Warning in install.packages :
  dependency ‘RCurl’ is not available
also installing the dependency ‘streamR’

  There are binary versions available but the source versions are later:
         binary source needs_compilation
streamR   0.2.1  0.4.5             FALSE
readtext   0.50   0.76             FALSE

installing the source packages ‘streamR’, ‘readtext’

trying URL 'https://mac.R-project.org/src/contrib/streamR_0.4.5.tar.gz'
Content type 'application/x-gzip' length 18257 bytes (17 KB)
==================================================
downloaded 17 KB

trying URL 'https://mac.R-project.org/src/contrib/readtext_0.76.tar.gz'
Content type 'application/x-gzip' length 3219787 bytes (3.1 MB)
==================================================
downloaded 3.1 MB

ERROR: dependency ‘RCurl’ is not available for package ‘streamR’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/streamR’
Warning in install.packages :
  installation of package ‘streamR’ had non-zero exit status
ERROR: dependency ‘streamR’ is not available for package ‘readtext’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/readtext’
Warning in install.packages :
  installation of package ‘readtext’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/r9/42bfgypx3hn6mwn6trtlr34m0000gn/T/RtmpM2Z6P8/downloaded_packages’

> sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X Yosemite 10.10.5

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.3.3

**Comment by kbenoit** [comment]
You are running a very old version of R, so I would suggest upgrading to the newest version supported by your OS (which is also quite old). That's likely why there are no binaries available for the dependency packages you need.
