### ISSUE TITLE
importing docvars from docx files

### ISSUE THREAD

**Issue by louislegum** [quanteda/readtext#168]
I am undertaking a  media content analysis and have downloaded DOCX files from nexus.com and am trying to import them into R. I have unzipped the file, and imported them using the readtext() but I cant seem to import the metadata associated with it. As it stands, I only have the doc_id (title) and the text. I was wondering whether you knew how I would extract docvars from the files such as the publisher or the date published.

**Comment by kbenoit** [comment]
@louislegum I think the above discussion has identified the issue as being some non-standard metadata issue, but I'd be happy to take a look nonetheless. Can you send me an example file and what you want to have extracted and how? Feel free to post the link here if it's not something you need to keep private.

**Comment by louislegum** [comment]
That would be great! I have attached an example docx file that I will be using in my analysis. Overall I am aiming to create a corpus of texts and use the metdata mentioned below to analysis them. 
 Ideally, the metadata I want to extract and create docvars with are the date of publishing ( which is always prefixed with "Load-Date") and the publisher which is the next line down from the title.

example docx: 
[](url)
[15 species that should be brought back to rewild Britain;From wolves to grey whales and lynxes, plan.DOCX](https://github.com/quanteda/readtext/files/8047865/15.species.that.should.be.brought.back.to.rewild.Britain.From.wolves.to.grey.whales.and.lynxes.plan.DOCX)

Thanks for the help!

**Comment by JBGruber** [comment]
I had another look at the files today and found that the problem is linked to this issue: https://github.com/JBGruber/LexisNexisTools/issues/14

So setting `remove_cover = FALSE` solves the problem.

**Comment by louislegum** [comment]
Ah amazing, thats seems to have worked! Thank you very much for all your help @JBGruber  and @kbenoit !
